# Factor to compute volume of material in m3 based on specific gravity in g/cm3 and mass in kg
G_CM3_TO_KG_M3_CONVERSION_FACTOR = 1000

MINMAX_DEFAULT_CONCRETE_POWDER_MIN = 350
MINMAX_DEFAULT_CONCRETE_POWDER_MAX = 450
MINMAX_DEFAULT_CONCRETE_POWDER_INC = 10

MINMAX_DEFAULT_CONCRETE_LIQUID_MIN = 35
MINMAX_DEFAULT_CONCRETE_LIQUID_MAX = 60
MINMAX_DEFAULT_CONCRETE_LIQUID_INC = 5

MINMAX_DEFAULT_CONCRETE_ADMIXTURE_MIN = 2
MINMAX_DEFAULT_CONCRETE_ADMIXTURE_MAX = 4
MINMAX_DEFAULT_CONCRETE_ADMIXTURE_INC = 1

MINMAX_DEFAULT_CONCRETE_CUSTOM_MIN = 0
MINMAX_DEFAULT_CONCRETE_CUSTOM_MAX = 20
MINMAX_DEFAULT_CONCRETE_CUSTOM_INC = 5

MINMAX_DEFAULT_BINDER_AGGREGATES_MIN = 50
MINMAX_DEFAULT_BINDER_AGGREGATES_MAX = 100
MINMAX_DEFAULT_BINDER_AGGREGATES_INC = 10

MINMAX_DEFAULT_BINDER_LIQUID_MIN = 35
MINMAX_DEFAULT_BINDER_LIQUID_MAX = 60
MINMAX_DEFAULT_BINDER_LIQUID_INC = 5

MINMAX_DEFAULT_BINDER_ADMIXTURE_MIN = 2
MINMAX_DEFAULT_BINDER_ADMIXTURE_MAX = 4
MINMAX_DEFAULT_BINDER_ADMIXTURE_INC = 1

MINMAX_DEFAULT_BINDER_CUSTOM_MIN = 0
MINMAX_DEFAULT_BINDER_CUSTOM_MAX = 20
MINMAX_DEFAULT_BINDER_CUSTOM_INC = 5