POWDER_DEFAULT_SPECIFIC_GRAVITY = 3.15
LIQUID_DEFAULT_SPECIFIC_GRAVITY = 1.05
AGGREGATE_DEFAULT_SPECIFIC_GRAVITY = 2.65
ADMIXTURE_DEFAULT_SPECIFIC_GRAVITY = 1.50
CUSTOM_DEFAULT_SPECIFIC_GRAVITY = 1.00